CREATE DATABASE [NECTIASOFTWARE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NECTIASOFTWARE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\NECTIASOFTWARE.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NECTIASOFTWARE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\NECTIASOFTWARE_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [NECTIASOFTWARE] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET ARITHABORT OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [NECTIASOFTWARE] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NECTIASOFTWARE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NECTIASOFTWARE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NECTIASOFTWARE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NECTIASOFTWARE] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NECTIASOFTWARE] SET  READ_WRITE 
GO
ALTER DATABASE [NECTIASOFTWARE] SET RECOVERY FULL 
GO
ALTER DATABASE [NECTIASOFTWARE] SET  MULTI_USER 
GO
ALTER DATABASE [NECTIASOFTWARE] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NECTIASOFTWARE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NECTIASOFTWARE] SET DELAYED_DURABILITY = DISABLED 
GO
USE [NECTIASOFTWARE]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [NECTIASOFTWARE]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [NECTIASOFTWARE] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

--  Aplicar comando en Solucion. Terminal. 
-- dotnet ef database update


CREATE TABLE Vehiculos (
    Id INT IDENTITY PRIMARY KEY,
    Marca NVARCHAR(100) NOT NULL,
    Modelo NVARCHAR(100) NOT NULL,
    Año INT NOT NULL
);



INSERT INTO Vehiculos (Marca, Modelo, Año)
VALUES 
('Toyota', 'Corolla', 2021),
('Honda', 'Civic', 2020),
('Ford', 'Focus', 2019);

